name: movemate
services:
  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:latest'
    ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: movemate12345!
    ports:
      - "27017:27017"